### ISSUE TITLE
Failed to parse manifest

### ISSUE THREAD

**Issue by AllanMangeni** [sapio-lang/sapio#163]
Hello, I am trying to build a package and instantiate a contract but I get this error

`Error: failed to parse manifest: /home/allan/sapio/plugin-example/Cargo.toml
Caused by: missing field `package`
`

**Comment by prayank23** [comment]
I got the same error today when I tried following all the steps shared in readme

**Comment by JeremyRubin** [comment]
hmmm sorry i missed this.

which directory are you building from?

**Comment by JeremyRubin** [comment]
can you also share your cargo version, clang/llvm version, and rust version? as well as `rustup target list`

**Comment by prayank23** [comment]
> which directory are you building from?

/sapio/plugin-example

![image](https://user-images.githubusercontent.com/13405205/148108854-5fe6804f-6ab4-466d-bc19-503daacdcff2.png)

> can you also share your cargo version, clang/llvm version, and rust version? as well as rustup target list

`cargo --version`: cargo 1.57.0 (b2e52d7ca 2021-10-21)

`locate clang`: returns nothing

`rustup target list`: https://pastebin.com/raw/eXDWyukP

**Comment by JeremyRubin** [comment]
ahh
can you just run 'cargo build --target wasm32-unknown-unknown'

**Comment by JeremyRubin** [comment]
where are you getting the wasm-pack instruction from btw

**Comment by prayank23** [comment]
> 

This works after installing clang

**Comment by prayank23** [comment]
> where are you getting the wasm-pack instruction from btw

Not sure. I just followed the steps mentioned here: https://github.com/sapio-lang/sapio#quickstart on a new Fedora VM installation

**Comment by JeremyRubin** [comment]
oh shoot!

follow the guide on learn.sapio-lang.org.

it's my bad, the readme is basically 100% out of sync with the book. Will cut that immediately.
