### ISSUE TITLE
Questions on Main Net Usage

### ISSUE THREAD

**Issue by xanderdunn** [sapio-lang/sapio#194]
These are questions rather than an issue report. I didn't find a Discord or Discussion tab on the GitHub repo, let me know if there's a better place for this. 

- Are you aware of any sapio contracts that are in use on bitcoin main net?
- [This doc page](https://learn.sapio-lang.org/ch05-02-taproot.html) writes "Without full Taproot support, Sapio is probably ill-advisable to use at writing". Is this outdated? I think taproot went live at block 709,631, right?
- My goal is a bitcoin main net script with the simple functionality of verifying signatures (Ideally ECDSA, but potentially other) from an authority, and updating who that authority is. The [payment pool example](https://github.com/sapio-lang/sapio/blob/9cc7fdf19db862e8ed57ecb842c8da103e606e65/plugin-example/payment_pool/src/payment_pool.rs) may be closest to this goal. Do you see this as a viable use case on bitcoin main net right now?

**Comment by JeremyRubin** [comment]
Hi @xanderdunn! Lemme give you the update:

- Yes, I did the Hanukkiah on mainnet this year
- Sapio does now have taproot support :)
- Yes, payment pools should be somewhat viable. Without CTV, the setup of a payment pool is harder though!

**Comment by JeremyRubin** [comment]
there is a discord btw and IRC.

https://discord.gg/wremMs9R

#sapio on libera

**Comment by xanderdunn** [comment]
Thanks very much @JeremyRubin, I'll close this and ask further questions on the Discord!
